apiVersion: v1
kind: Secret
metadata:
  name: gcr-json-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <Enter the GCP key in Base64Format> #Warning! Do not keep the actual key in a public repository
  