apiVersion: v1
kind: Service
metadata:
  name: {{ include "dokuwiki.fullname" . }}
  labels:
    {{- include "dokuwiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{.Values.containerPortHttp.name}}
      port: {{ .Values.service.port }}
      targetPort: {{.Values.containerPortHttp.port}}

    - name: {{.Values.containerPortHttps.name}}
      port: {{ .Values.service.ports }}
      targetPort: {{.Values.containerPortHttps.port}}

  selector:
    {{- include "dokuwiki.selectorLabels" . | nindent 4 }}
