apiVersion: v1
kind: Service
metadata:
  name: {{ include "dokuwiki.fullname" . }}
  labels:
    {{- include "dokuwiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8089
      targetPort: 8080

    - name: https
      port: 443
      targetPort: 8443

  selector:
    {{- include "dokuwiki.selectorLabels" . | nindent 4 }}
